### ISSUE TITLE
Security problem

### ISSUE THREAD

**Issue by xnnkmd** [conclurer/markdown-to-html-pipe#10]
The free [nsp ](https://github.com/nodesecurity/nsp) security check tool reports a problem with your package. Thus I am unable to use it. I think you can fix the issues by upgrading the version(s) of your dependencies (some are pretty old):

Here is the output from the tool:

┌───────────────┬───────────────────────────────────────────────────────────────────────────────────────────────┐
│               │ Regular Expression Denial of Service                                                          │
├───────────────┼───────────────────────────────────────────────────────────────────────────────────────────────┤
│ Name          │ marked                                                                                        │
├───────────────┼───────────────────────────────────────────────────────────────────────────────────────────────┤
│ CVSS          │ 7.5 (High)                                                                                    │
├───────────────┼───────────────────────────────────────────────────────────────────────────────────────────────┤
│ Installed     │ 0.3.6                                                                                         │
├───────────────┼───────────────────────────────────────────────────────────────────────────────────────────────┤
│ Vulnerable    │ All                                                                                           │
├───────────────┼───────────────────────────────────────────────────────────────────────────────────────────────┤
│ Patched       │ None                                                                                          │
├───────────────┼───────────────────────────────────────────────────────────────────────────────────────────────┤
│ Path          │ ... > markdown-to-html-pipe@1.2.3 > marked@0.3.6                                    │
├───────────────┼───────────────────────────────────────────────────────────────────────────────────────────────┤
│ More Info     │ https://nodesecurity.io/advisories/531                                                        │
└───────────────┴───────────────────────────────────────────────────────────────────────────────────────────────┘

**Comment by vknabel** [comment]
@xnnkmd Thanks for your feedback.
The security problem is one of `marked`, not of `markdown-to-html-pipe`, which already uses the latest version of `marked` available.

Maybe we should rely on a fork of `marked` or create a new pipe relying on a different markdown parser.

**Comment by vknabel** [comment]
@xnnkmd As an alternative you may use [@molecule/markdown](https://github.com/vknabel/molecule-markdown), which allows you to implement the markdown conversion with any library you wish.
