### ISSUE TITLE
Dependency on marked@0.3.7 which has security vulnerability

### ISSUE THREAD

**Issue by lastrader** [conclurer/markdown-to-html-pipe#12]
A new build would pull in the patched version of marked.
https://nodesecurity.io/advisories/531

**Comment by vknabel** [comment]
Thanks for your feedback!
Currently this package uses [`marked@^0.x`](https://github.com/conclurer/markdown-to-html-pipe/blob/1.2.4/package.json#L55) which should automatically be updated to `0.3.19`.

Do you use some kind of lockfile like `package.json.lock` or `yarn.lock`? In that case you just need to update marked.
