### ISSUE TITLE
Update package dependencies for angular 6

### ISSUE THREAD

**Issue by sp-eric-pinto** [conclurer/markdown-to-html-pipe#13]
The latests version of node is not supported by your packages dependencies.

![image](https://user-images.githubusercontent.com/16895475/40127923-ba2da130-5930-11e8-9d26-9d0c4cdd744f.png)

**Comment by vknabel** [comment]
Thanks for your feedback. AFAIK this should still be compatible with Angular 6 even if the installation warning isn’t that nice. The next update will explicitly support Angular 6.
