### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by isametal88** [conclurer/markdown-to-html-pipe#2]
Hi,

is it possible to upgrade the rxjs dependency in your component?
It seems to work fine with the most recent version (beta.11) but I can't add your plugin to my package.json (i have to install it manually every time).

Thank you very much

P.s.: I'm new to npm and angular, I'm sorry if I wrote something stupid :-)

Isaia

**Comment by marvinscharle** [comment]
Updated dependency in commit.
