### ISSUE TITLE
Compiling for AOT fails

### ISSUE THREAD

**Issue by invegat** [conclurer/markdown-to-html-pipe#4]
Error: Type MarkdownToHtmlPipe in E:/angutype/node_modules/markdown-to-html-pipe/src/markdown-to-html.pipe.d.ts is part of the declarations of 2 modules: MarkdownToHtm
lModule in E:/angutype/node_modules/markdown-to-html-pipe/index.d.ts and AtAppModule in E:/angutype/src/app/AT/At.module.ts! Please consider moving MarkdownToHtmlPipe
in E:/angutype/node_modules/markdown-to-html-pipe/src/markdown-to-html.pipe.d.ts to a higher module that imports MarkdownToHtmlModule in E:/angutype/node_modules/markd
own-to-html-pipe/index.d.ts and AtAppModule in E:/angutype/src/app/AT/At.module.ts. You can also create a new NgModule that exports and includes MarkdownToHtmlPipe in
E:/angutype/node_modules/markdown-to-html-pipe/src/markdown-to-html.pipe.d.ts then import that NgModule in MarkdownToHtmlModule in E:/angutype/node_modules/markdown-to
-html-pipe/index.d.ts and AtAppModule in E:/angutype/src/app/AT/At.module.ts.

**Comment by vknabel** [comment]
@invegat Thanks for your feedback.

Did you create the module `AtAppModule`?
It seems like `AtAppModule` declares `MarkdownToHtmlPipe` as component. Instead it should import the module.

You need to edit your `@NgModule` in `E:/angutype/src/app/AT/At.module.ts` to import `MarkdownToHtmlModule` instead of declaring `MarkdownToHtmlPipe` as follows:

```typescript
import {MarkdownToHtmlModule} from 'markdown-to-html-pipe'; // you just need to import MarkdownToHtmlModule

@NgModule({
    imports: [
        MarkdownToHtmlModule // Additionally import MarkdownToHtmlModule
    ],
    declarations: [
         // remove MarkdownToHtmlPipe from here
    ]
})
export class AtAppModule { }
```

I hope this solves your problem!

**Comment by zbicin** [comment]
@vknabel FYI it worked for me, thanks. :) 

The README.md is a little bit misleading though, I've imported the pipe and declared it in a module, like @invegat probably did.
