### ISSUE TITLE
Unmet peer dependency

### ISSUE THREAD

**Issue by nbijl** [conclurer/markdown-to-html-pipe#6]
Hi, 
i got this warning: 
npm WARN markdown-to-html-pipe@1.2.0 requires a peer of @angular/core@^2.0.0 but none was installed.

Any idea what to do about this?
we are using these packages: 
"dependencies": {
        "@angular/animations": "^4.1.2",
        "@angular/common": "^4.1.2",
        "@angular/compiler": "^4.1.2",
        "@angular/core": "^4.1.2",
        "@angular/forms": "^4.1.2",
        "@angular/http": "^4.1.2",
        "@angular/platform-browser": "^4.1.2",
        "@angular/platform-browser-dynamic": "^4.1.2",
        "@angular/router": "^4.1.2",
        "angular-2-local-storage": "^1.0.1",
        "angular2-jwt": "^0.2.3",
        "angular2-moment": "^1.1.0",
        "core-js": "^2.4.1",
        "markdown-to-html-pipe": "^1.2.0",
        "ng2-translate": "^5.0.0",
        "ngx-bootstrap": "^1.6.6",
        "ngx-clipboard": "^8.0.2",
        "rxjs": "^5.2.0",
        "web-animations-js": "^2.2.2",
        "zone.js": "^0.8.4"
    },

Thanks

**Comment by vknabel** [comment]
@nbijl Thanks for your feedback!

The warning was harmless as `markdown-to-html-pipe` did actually work with Angular 4, too.

I just released a new update as `markdown-to-html-pipe@1.2.1` in order to represent this compatibility.
