### ISSUE TITLE
Support for checkboxes

### ISSUE THREAD

**Issue by karllhughes** [conclurer/markdown-to-html-pipe#7]
I know these aren't standard in all flavors of markdown, but any interest in supporting [Github's style of checkboxes](https://github.com/blog/1825-task-lists-in-all-markdown-documents) in this package?

This example:

```
- [ ] An unchecked checkbox
- [x] A checked checkbox
```

Would render as it does on Github:

- [ ] An unchecked checkbox
- [x] A checked checkbox

**Comment by karllhughes** [comment]
Didn't really notice, but [this is in the works (possibly) for chjj/marked](https://github.com/chjj/marked/pull/587), so I'm guessing when it's merged in there it will also work in this package, yes?

**Comment by vknabel** [comment]
@karllhughes Yes. If https://github.com/chjj/marked/pull/587 will be merged, `markdown-to-html-pipe` will support checkboxes.

**Comment by vknabel** [comment]
@karllhughes With `markdown-to-html-pipe@1.2.2` chjj/marked is now a peer dependency. 
That way you can temporarily replace chjj/marked with jhollingworth/marked. Once the PR will be merged and released, even versions like `0.4.0` or `1.0.0` wouldn't require an update to `markdown-to-html-pipe`.

If there are any other issues or suggestions, feel free to ask.
